version: "3"
services:
    web:
      image: ijse/koaplate
      deploy:
        replicas: 5
        resources:
          limits:
            cpus: "0.1"
            memory: 500M
        restart_policy:
          condition: on-failure
      ports:
        - "4000:4000"
      networks:
        - webnet
networks:
  webnet:
